server:
  port: 8810

spring:
  application:
    name: quick-service
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/quick_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8800/eureka/

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
#  type-aliases-package: org.xi.quick.codegenerator.mapper

logging:
  level: info