
server:
  port: 8920

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study_order?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 10.16.1.136
    port: 5672
    username: admin
    password: 123456
  sleuth:
    sampler:
      percentage: 1.0
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: org.xi.quick.codegenerator.mapper

management:
  security:
    enabled: false

# 熔断必须要下面一段
feign:
  hystrix:
    enabled: true
logging:
  level: info

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"